spring:
  application:
    name: car-procurement-app
  boot:
    admin:
      client:
        # Where the Spring boot admin resides
        url: http://localhost:8100
        # When shut down deregisters from spring boot admin
        auto-deregistration: true
server:
  # Allow for automatic available port allocation
  port: 0
  error:
    # e.g. when an 500 error is displayed will have the underlying error message
    include-message: always
logging:
  file:
    name: car-procurement-app.log
    max-history: 5
    max-size: 10MB
management:
  endpoint:
    env:
      # show the values in actuator/env endpoint
      # e.g. http://localhost:8101/actuator/env
      show-values: ALWAYS
    configprops:
      # show the values in actuator/configprops endpoint
      # e.g. http://localhost:8101/actuator/configprops
      show-values: ALWAYS
    health:
      # Note show-details
      show-details: ALWAYS
    shutdown:
      enabled: true
  endpoints:
    enabledByDefault: true
    env:
      # mask these values in actuator/env endpoint
      keys-to-sanitize: password,secret
    configprops:
      # mask these values in actuator/configprops endpoint
      keys-to-sanitize: password,secret
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
    build:
      enabled: true
    git:
      # All the GIT info
      mode: full
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}:${random.value}}
# Application data to prime the in memory database - TEST purposes only
application-data:
  transactionRecords:
    - id: 1
      car:
        id: 1
        registrationPlate: LL62MVF
        make: Porsche
        model: Cayenne
        type: SUV
        capacity: 5
      transactionType: BUY
      transactionDate: 2015-12-16
      amount: 43500.00
    - id: 2
      car:
        id: 1
        registrationPlate: LL62MVF
        make: Porsche
        model: Cayenne
        type: SUV
        capacity: 5
      transactionType: SELL
      transactionDate: 2023-01-30
      amount: 14500.00
    - id: 3
      car:
        id: 2
        registrationPlate: LL15RDF
        make: Range Rover
        model: Discovery
        type: SUV
        capacity: 7
        location:
          id: 1
          locationName: Toronto
      transactionType: BUY
      transactionDate: 2023-01-30
      amount: 53000.00
  locations:
    - id: 1
      locationName: Toronto
    - id: 2
      locationName: Vancouver
    - id: 3
      locationName: Ottawa
  cars:
    - id: 1
      registrationPlate: LL72MVF
      make: Porsche
      model: Cayenne
      type: SUV
      capacity: 5
      location:
        id: 1
        locationName: Toronto
    - id: 2
      registrationPlate: LL15RDF
      make: Range Rover
      model: Discovery
      type: SUV
      capacity: 7
      location:
        id: 1
        locationName: Toronto
    - id: 3
      registrationPlate: LL23UBS
      make: BMW
      model: 520D
      type: Sedan
      capacity: 5
      location:
        id: 2
        locationName: Vancouver
    - id: 4
      registrationPlate: LL45UBS
      make: Lincoln
      model: Navigator
      type: SUV
      capacity: 7
      location:
        id: 2
        locationName: Vancouver
    - id: 5
      registrationPlate: LL45UBS
      make: Tesla
      model: Model S
      type: Sedan
      capacity: 5
      location:
        id: 3
        locationName: Ottawa
    - id: 6
      registrationPlate: LL45UBS
      make: Tesla
      model: Model X
      type: SUV
      capacity: 7
      location:
        id: 3
        locationName: Ottawa